### ISSUE TITLE
IO error 

### ISSUE THREAD

**Issue by muthuku** [CederGroupHub/MatEntityRecognition#25]
I installed the github repo for MatEntityRecognition and I also cloned the MaterialParser one, I tried to run an example on python so I typed in "from materials_entity_recognition import MatRecognition", and I got this error 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/__init__.py", line 1, in <module>
    from .scripts import MatRecognition
  File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/__init__.py", line 3, in <module>
    from .mat_models import MatIdentification
  File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/mat_models.py", line 8, in <module>
    from .model_framework import NERModel
  File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/model_framework.py", line 19, in <module>
    from .loader import get_input_format, dict_to_tf_dataset
  File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/loader.py", line 28, in <module>
    nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 51, in load
    name, vocab=vocab, disable=disable, exclude=exclude, config=config
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 331, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

Im not sure what this means and any help would be appreciated on how to get this running. Also where exactly do we install the MaterialParser package, is it within the matEntityRecognition folder or somewhere else

**Comment by zhugeyicixin** [comment]
As mentioned in ReadMe, spacy is used. The error "Can't find model 'en-core-web-sm'" is because the spacy data is not downloaded. Please use:
    python -m spacy download en-core-web-sm
That should address the problem. Please feel free to follow up if you had further questions.
