### ISSUE TITLE
OpError

### ISSUE THREAD

**Issue by mostly-harmless-earth** [CederGroupHub/MatEntityRecognition#28]
I installed the github repo for MatEntityRecognition and I also cloned the MaterialParser one, I tried to run an example on python so I use the example in the test, and I got this error: 

2023-03-26 17:24:04.418474: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
lr_method_name, lr_method_parameters adamdecay {'lr': 1e-05, 'epsilon': 1e-08, 'warmup': 0.1}
num_train_steps, num_warmup_steps 250000 25000
classifier_type lstm
2023-03-26 17:24:05.125656: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss.
Traceback (most recent call last):
  File "D:\aconcon\envs\raw1\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 71, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\rawscrpit\text-mined-synthesis_public\MatEntityRecognition\MatEntityRecognition\materials_entity_recognition\scripts\mat_models.py", line 642, in __init__
    self.model = NERModel.reload_model(model_path=self.model_path, bert_path=self.bert_path)
  File "D:\rawscrpit\text-mined-synthesis_public\MatEntityRecognition\MatEntityRecognition\materials_entity_recognition\scripts\model_framework.py", line 948, in reload_model
    model.load_weights(cp_path)
  File "D:\aconcon\envs\raw1\lib\site-packages\keras\engine\training.py", line 2331, in load_weights
    status = self._trackable_saver.restore(filepath, options)
  File "D:\aconcon\envs\raw1\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1345, in restore
    object_graph_string = reader.get_tensor(base.OBJECT_GRAPH_PROTO_KEY)
  File "D:\aconcon\envs\raw1\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 75, in get_tensor
    error_translator(e)
  File "D:\aconcon\envs\raw1\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 49, in error_translator
    raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN)
tensorflow.python.framework.errors_impl.OpError

Im not sure what this means and any help would be appreciated on how to get this running.

**Comment by zhugeyicixin** [comment]
This issue likely stems from a version compatibility problem among different packages. I've updated the setup.py file, which should resolve the issue. If the problem persists, consider installing a specific version of transformers using the following command: pip install transformers==4.11.3. I have tested versions from 4.11.3 to 4.34.0 of transformers, and all have worked as expected.
